// Data fetching constants
export const LOAD_STOCK_STATISTICS_REQUEST = 'LOAD_STOCK_STATISTICS_REQUEST'
export const LOAD_STOCK_STATISTICS_SUCCESS = 'LOAD_STOCK_STATISTICS_SUCCESS'
export const LOAD_STOCK_STATISTICS_ERROR = 'LOAD_STOCK_STATISTICS_ERROR'
