// Data fetching constants
export const LOAD_STOCK_STATISTICS_REQUEST = 'LOAD_STOCK_STATISTICS_REQUEST'
export const LOAD_STOCK_STATISTICS_SUCCESS = 'LOAD_STOCK_STATISTICS_SUCCESS'
export const LOAD_STOCK_STATISTICS_ERROR = 'LOAD_STOCK_STATISTICS_ERROR'
export const UPDATE_STOCK_STATISTICS_REQUEST = 'UPDATE_STOCK_STATISTICS_REQUEST'
export const UPDATE_STOCK_STATISTICS_SUCCESS = 'UPDATE_STOCK_STATISTICS_SUCCESS'
export const UPDATE_STOCK_STATISTICS_ERROR = 'UPDATE_STOCK_STATISTICS_ERROR'
export const UPDATE_LAST_FETCHED_TIME = 'UPDATE_LAST_FETCHED_TIME'
